import "../styles/global.css";
import ReduxProvider from "../store/ReduxProvider";
import AuthInit from "../components/Init/AuthInit";
import Navbar from "../components/Navbar/Navbar";

export const metadata = {
  title: "Shopwise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <AuthInit />
          <Navbar />
          <main>{children}</main>
          <footer
            style={{
              marginTop: "2rem",
              padding: "1rem",
              borderTop: "1px solid #49416D",
            }}
          >
            Shopwise &copy; {new Date().getFullYear()}
          </footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
