import "../styles/global.css";
import ReduxProvider from "../store/ReduxProvider";

export const metadata = {
  title: "Shopwise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <nav>
            {/* Placeholder navbar */}
            <div style={{ padding: "1rem", borderBottom: "1px solid #49416D" }}>
              <a href="/">Shopwise</a> | <a href="/cart">Cart</a>
            </div>
          </nav>
          <main>{children}</main>
          <footer
            style={{
              marginTop: "2rem",
              padding: "1rem",
              borderTop: "1px solid #49416D",
            }}
          >
            Shopwise &copy; {new Date().getFullYear()}
          </footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
